{
    'name': 'pabs_settlement',
    'category': 'hr',
    'summary': 'Settlement Customization',
    'version': '1.0',
    'description': """Customization of Settlement module as per requirement.""",
    'depends': ['base', 'hr_payroll', 'hr', 'hr_holidays', 'hr_holidays_attendance', 'hr_work_entry',
                'hr_payroll_account', 'hr_skills', 'hr_loan', 'pabs_hr'],
    'data': [
        'security/ir.model.access.csv',
        'data/report_paperformat.xml',
        'data/rules.xml',
        'views/hr_settlement.xml',
        'views/settelment_type.xml',
        'views/final_settlement_report.xml',
        'views/hr_leave_type.xml',
        'views/hr_payslip_view.xml',
        'reports/final_settlement_printout.xml',
        'reports/annual_leave_settlement_printout.xml',
        'reports/vacation_settlement_printout.xml',
        'wizard/review_loans.xml',
    ],
    'installable': True,
    'auto_install': False,
}
