from . import model
from . import settlement_type
from . import indemnity
from . import leaving_reason
from . import inputs_line
from . import vacation_payment
from . import employee_leaves
from . import encashment_lines
from . import deduction_days
from . import anual_provision
from . import indeminity_provision
from . import leave_type
from . import encashment_vacation_payment_lines
from . import indeminity_vacation_payment_lines
from . import hr_payslip