from odoo import models


class BatchPayslipXLS(models.AbstractModel):
    _name = 'report.pabs_hr.report_employee_details_xls'
    _inherit = 'report.odoo_report_xlsx.abstract'

    # def compute_sheet(self, id):
    #     slips = self.env['hr.payslip'].search([('payslip_run_id', '=', id)])
    #     print(slips.mapped('line_ids'), 'line_ids')
    #     # for rec in slips.line_ids:

    def generate_xlsx_report(self, workbook, data, lines):
        # self.compute_sheet(lines.id)
        format = workbook.add_format({'font_size': 16, 'align': 'vcenter', 'bold': True})
        format1 = workbook.add_format({'font_size': 14, 'align': 'vcenter'})
        format2 = workbook.add_format({'font_size': 16, 'text_wrap': True, 'num_format': 'yyyy-mm-dd'})

        sheet = workbook.add_worksheet('Salary Compensation')
        sheet.write(0, 0, 'Code', format)
        sheet.write(0, 1, 'Department', format)
        sheet.write(0, 2, 'Name', format)
        sheet.write(0, 3, 'CPR', format)
        sheet.write(0, 4, 'Date of Join', format)
        sheet.write(0, 5, 'Gosi Salary', format)
        sheet.write(0, 6, 'Sio Employer Contribution', format)
        sheet.write(0, 7, 'Sio Employee Deduction', format)
        sheet.write(0, 8, 'Basic', format)
        sheet.write(0, 9, 'Home Rent Allowance', format)
        sheet.write(0, 10, 'Other Allowance', format)
        sheet.write(0, 11, 'Transportation Allowance', format)
        sheet.write(0, 12, 'Special Allowance', format)
        sheet.write(0, 13, 'Shift Allowance', format)
        sheet.write(0, 14, 'Food Allowance', format)
        sheet.write(0, 15, 'Increment Allowance', format)
        sheet.write(0, 16, 'Social Allowance', format)
        sheet.write(0, 17, 'Labour Allowance', format)
        sheet.write(0, 18, 'Phone Allowance', format)
        sheet.write(0, 19, 'Performance Allowance', format)
        sheet.write(0, 20, 'Under CR', format)
        sheet.write(0, 21, 'Designation', format)
        sheet.write(0, 22, 'Bank Name', format)
        sheet.write(0, 23, 'City', format)
        sheet.write(0, 24, 'Work Email.', format)
        sheet.write(0, 25, 'Private Email', format)
        sheet.write(0, 26, 'Company No', format)
        sheet.write(0, 27, 'IBAN', format)
        sheet.write(0, 28, 'Loan', format)
        sheet.write(0, 29, 'Payment Method', format)
        sheet.write(0, 30, 'Period of Contract', format)
        sheet.write(0, 31, 'Sio Applicable', format)
        sheet.write(0, 32, 'Phone', format)
        sheet.write(0, 33, 'Mobile', format)
        sheet.write(0, 34, 'Date of Birth', format)
        sheet.write(0, 35, 'Visa No', format)
        sheet.write(0, 36, 'Visa Expiry', format)
        sheet.write(0, 37, 'Visa Issue', format)
        sheet.write(0, 38, 'Passport Expiry Date', format)
        sheet.write(0, 39, 'Passport Issue Date', format)
        sheet.write(0, 40, 'Passport NO', format)
        sheet.write(0, 41, 'Passport Issue Place', format)
        sheet.write(0, 42, 'Nationality', format)
        sheet.write(0, 43, 'Permanent Address', format)
        sheet.write(0, 44, 'Contract Expiry Date', format)
        sheet.write(0, 45, 'Contract Type', format)
        sheet.write(0, 46, 'Category', format)
        sheet.write(0, 47, 'Probation Period', format)
        sheet.write(0, 48, 'Driving Licence Expiry', format)
        sheet.write(0, 49, 'Status', format)
        sheet.write(0, 50, 'Gender', format)
        sheet.write(0, 51, 'Employee Status', format)
        sheet.write(0, 52, 'Last Vacation Date', format)
        sheet.write(0, 53, 'Last Return Date', format)
        sheet.write(0, 54, 'Worked Days', format)
        sheet.write(0, 55, 'Address', format)
        sheet.write(0, 56, 'Contract No', format)
        sheet.write(0, 57, 'Short Name', format)
        sheet.write(0, 58, 'Remaining Annual Leave', format)
        sheet.write(0, 59, 'Remaining Full Paid Sick Leave', format)
        sheet.write(0, 60, 'Remaining Half Paid Sick Leave', format)
        sheet.write(0, 61, 'Remaining Unpaid Leave', format)
        # sheet.write(0, 62, 'Remaining Overtime Leave', format)
        # sheet.write(0, 63, 'Remaining Unpaid', format)
        i = 1
        for line in lines:
            # print(line, "aaaaaa")
            # print(lines, "sssss")
            # for slip in line.mapped('slip_ids'):
            sheet.write(i, 0, line.registration_number, format1)
            sheet.write(i, 1, line.department_id.name, format1)
            sheet.write(i, 2, line.name, format1)
            sheet.write(i, 3, line.identification_id, format1)
            sheet.write(i, 4, line.date_of_join, format2)
            sheet.write(i, 5, line.contract_id.gosi_salary, format1)
            sheet.write(i, 6, line.contract_id.sio_employer_contribution_amount, format1)
            sheet.write(i, 7, line.contract_id.sio_employee_deduction_amount, format1)
            sheet.write(i, 8, line.contract_id.wage, format1)
            sheet.write(i, 9, line.contract_id.home_rent_allowance, format1)
            sheet.write(i, 10, line.contract_id.other_allowance, format1)
            sheet.write(i, 11, line.contract_id.transportation_allowance, format1)
            sheet.write(i, 12, line.contract_id.special_allowance, format1)
            sheet.write(i, 13, line.contract_id.shift_allowance, format1)
            sheet.write(i, 14, line.contract_id.food_allowance, format1)
            sheet.write(i, 15, line.contract_id.increments, format1)
            sheet.write(i, 16, line.contract_id.social_allowance, format1)
            sheet.write(i, 17, line.contract_id.labour_allowance, format1)
            sheet.write(i, 18, line.contract_id.phone_allowance, format1)
            sheet.write(i, 19, line.contract_id.performance_allowance, format1)
            sheet.write(i, 20, line.cr_no, format1)
            sheet.write(i, 21, line.job_id.name, format1)
            sheet.write(i, 22, line.bank_account_id.bank_id.name, format1)
            sheet.write(i, 23, line.address_home_id.city, format1)
            sheet.write(i, 24, line.work_email, format1)
            sheet.write(i, 25, line.private_email, format1)
            sheet.write(i, 26, line.company_id.phone, format1)
            sheet.write(i, 27, line.x_iban, format1)
            sheet.write(i, 28, line.loan_availability, format1)
            sheet.write(i, 29, line.payment_method, format1)
            sheet.write(i, 30, line.contract_id.contract_type.name, format1)
            sheet.write(i, 31, line.contract_id.sio_applicable, format1)
            sheet.write(i, 32, line.phone, format1)
            sheet.write(i, 33, line.mobile, format1)
            sheet.write(i, 34, line.birthday, format2)
            sheet.write(i, 35, line.visa_no, format1)
            sheet.write(i, 36, line.visa_expire, format2)
            sheet.write(i, 37, line.visa_issue_date, format2)
            sheet.write(i, 38, line.passport_expiration, format2)
            sheet.write(i, 39, line.passport_issue_date, format2)
            sheet.write(i, 40, line.passport_id, format1)
            sheet.write(i, 41, line.passport_issue_place.name, format1)
            sheet.write(i, 42, line.country_id.name, format1)
            sheet.write(i, 43, str(line.address_home_id.street) + str(line.address_home_id.city),
                        format1)
            sheet.write(i, 44, line.contract_id.date_end, format2)
            sheet.write(i, 45, line.contract_id.contract_type.name, format1)
            sheet.write(i, 46, line.contract_id.contract_category.name, format1)
            sheet.write(i, 47, line.contract_id.trial_date_end, format2)
            sheet.write(i, 48, line.license_expiration, format1)
            sheet.write(i, 49, line.x_is_expats, format1)
            sheet.write(i, 50, line.gender, format1)
            sheet.write(i, 51, line.employee_status, format1)
            sheet.write(i, 52, line.x_last_annual_leave, format2)
            sheet.write(i, 53, line.x_last_annual_leave_return, format2)
            sheet.write(i, 54, line.x_duration_of_work, format1)
            sheet.write(i, 55, line.x_country_address, format1)
            sheet.write(i, 56, line.contract_id.name, format1)
            sheet.write(i, 57, line.short_name, format1)
            sheet.write(i, 58, line.x_annual_leave, format1)
            sheet.write(i, 59, line.x_full_paid, format1)
            sheet.write(i, 60, line.x_half_paid, format1)
            sheet.write(i, 61, line.x_unpaid_sick, format1)
            i += 1
