from odoo import models


class BatchPayslipXLS(models.AbstractModel):
    _name = 'report.pabs_payroll.report_transfer_request_xls'
    _inherit = 'report.odoo_report_xlsx.abstract'

    # def compute_sheet(self, id):
    #     slips = self.env['hr.payslip'].search([('payslip_run_id', '=', id)])
    #     print(slips.mapped('line_ids'), 'line_ids')
    #     # for rec in slips.line_ids:

    def generate_xlsx_report(self, workbook, data, lines):
        # self.compute_sheet(lines.id)
        format = workbook.add_format({'font_size': 16, 'align': 'vcenter', 'bold': True})
        format1 = workbook.add_format({'font_size': 14, 'align': 'vcenter'})
        sheet = workbook.add_worksheet('Salary Compensation')
        sheet.write(0, 0, 'Department', format)
        sheet.write(0, 1, 'Category', format)
        sheet.write(0, 2, 'CPR', format)
        sheet.write(0, 3, 'Nationality', format)
        sheet.write(0, 4, 'Payment Method', format)
        sheet.write(0, 5, 'Code', format)
        sheet.write(0, 6, 'Name', format)
        sheet.write(0, 7, 'Gosi', format)
        sheet.write(0, 8, 'Basic', format)
        sheet.write(0, 9, 'Working Days', format)
        sheet.write(0, 10, 'Sick Leave', format)
        sheet.write(0, 11, 'Death Leave', format)
        sheet.write(0, 12, 'Unpaid Leave', format)
        sheet.write(0, 13, 'Shortage', format)
        sheet.write(0, 14, 'Overtime Leave', format)
        sheet.write(0, 15, 'Hajj Leave', format)
        sheet.write(0, 16, 'Annual Leave', format)
        sheet.write(0, 17, 'Maternity Leave', format)
        sheet.write(0, 18, 'Abesntism', format)
        sheet.write(0, 19, 'Half Sick Leave', format)
        sheet.write(0, 20, 'Unpaid Sick Leave', format)
        sheet.write(0, 21, 'Other Leave', format)
        sheet.write(0, 22, 'Marriage Leave', format)
        sheet.write(0, 23, '1.25 Overtime Hour', format)
        sheet.write(0, 24, '1.25 Overtime Amount', format)
        sheet.write(0, 25, '1.5 Overtime Hour.', format)
        sheet.write(0, 26, '1.5 Overtime Amount', format)
        sheet.write(0, 27, '2.0 Overtime Hour', format)
        sheet.write(0, 28, '2.0 Overtime Amount', format)
        sheet.write(0, 29, 'Home Rent Allowance', format)
        sheet.write(0, 30, 'Other Allowance', format)
        sheet.write(0, 31, 'Transportation Allowance', format)
        sheet.write(0, 32, 'Special Allowance', format)
        sheet.write(0, 33, 'Shift Allowance', format)
        sheet.write(0, 34, 'Food Allowance', format)
        sheet.write(0, 35, 'Increment Allowance', format)
        sheet.write(0, 36, 'Miscellaneous  Earning', format)
        sheet.write(0, 37, 'Social Allowance', format)
        sheet.write(0, 38, 'Labour Allowance', format)
        sheet.write(0, 39, 'Phone Allowance', format)
        sheet.write(0, 40, 'Performance Allowance', format)
        sheet.write(0, 41, 'Bonus', format)
        sheet.write(0, 42, 'Reward', format)
        sheet.write(0, 43, 'Incentives', format)
        sheet.write(0, 44, 'Commission', format)
        sheet.write(0, 45, 'Installment Refunds', format)
        sheet.write(0, 46, 'Total Earnings', format)
        sheet.write(0, 47, 'Sio Employee Deduction', format)
        sheet.write(0, 48, 'Miscellaneous Deduction', format)
        sheet.write(0, 49, 'Fixed Salary', format)
        sheet.write(0, 50, 'Staff Loan', format)
        sheet.write(0, 51, 'Penalty', format)
        sheet.write(0, 52, 'Advance Salary', format)
        sheet.write(0, 53, 'Credit Purchase', format)
        sheet.write(0, 54, 'Day Deduction', format)
        sheet.write(0, 55, 'Traffic Fine', format)
        sheet.write(0, 56, 'Total Deductions', format)
        sheet.write(0, 57, 'Gross Salary', format)
        sheet.write(0, 58, 'Net', format)
        sheet.write(0, 59, 'Remarks', format)

        i = 1
        for line in lines:
            for slip in line.mapped('slip_ids'):
                sheet.write(i, 0, slip.employee_id.department_id.name, format1)
                sheet.write(i, 1, slip.employee_id.contract_id.contract_category.name, format1)
                sheet.write(i, 2, slip.employee_id.identification_id, format1)
                sheet.write(i, 3, slip.employee_id.country_id.name, format1)
                sheet.write(i, 4, slip.employee_id.payment_method, format1)
                sheet.write(i, 5, slip.employee_id.registration_number, format1)
                sheet.write(i, 6, slip.employee_id.name, format1)
                sheet.write(i, 7, slip.employee_id.contract_id.gosi_salary, format1)
                sheet.write(i, 8, slip.basic_wage, format1)
                sheet.write(i, 9, slip.attendance, format1)
                sheet.write(i, 10, slip.sick_leave, format1)
                sheet.write(i, 11, slip.death_leave, format1)
                sheet.write(i, 12, slip.unpaid_leaves, format1)
                sheet.write(i, 13, slip.shortage, format1)
                sheet.write(i, 14, slip.overtime_leave, format1)
                sheet.write(i, 15, slip.hajj_leave, format1)
                sheet.write(i, 16, slip.annual_leave, format1)
                sheet.write(i, 17, slip.maternity_leave, format1)
                sheet.write(i, 18, slip.absent, format1)
                sheet.write(i, 19, slip.half_sick_leave, format1)
                sheet.write(i, 20, slip.unpaid_leave, format1)
                sheet.write(i, 21, slip.other_leave, format1)
                sheet.write(i, 22, slip.marriage_leave, format1)
                sheet.write(i, 23, slip.overtime_hour, format1)
                sheet.write(i, 24, slip.overtime_amount, format1)
                sheet.write(i, 25, slip.holiday_overtime_hour, format1)
                sheet.write(i, 26, slip.holiday_overtime_amount, format1)
                sheet.write(i, 27, slip.weekly_off_overtime_hour, format1)
                sheet.write(i, 28, slip.weekly_off_overtime_amount, format1)
                sheet.write(i, 29, slip.employee_id.contract_id.home_rent_allowance, format1)
                sheet.write(i, 30, slip.employee_id.contract_id.other_allowance, format1)
                sheet.write(i, 31, slip.employee_id.contract_id.transportation_allowance, format1)
                sheet.write(i, 32, slip.employee_id.contract_id.special_allowance, format1)
                sheet.write(i, 33, slip.employee_id.contract_id.shift_allowance, format1)
                sheet.write(i, 34, slip.employee_id.contract_id.food_allowance, format1)
                sheet.write(i, 35, slip.employee_id.contract_id.increments, format1)
                sheet.write(i, 36, slip.miscellaneous_earning, format1)
                sheet.write(i, 37, slip.employee_id.contract_id.social_allowance, format1)
                sheet.write(i, 38, slip.employee_id.contract_id.labour_allowance, format1)
                sheet.write(i, 39, slip.employee_id.contract_id.phone_allowance, format1)
                sheet.write(i, 40, slip.employee_id.contract_id.performance_allowance, format1)
                sheet.write(i, 41, slip.bonus, format1)
                sheet.write(i, 42, slip.reward, format1)
                sheet.write(i, 43, slip.incentives, format1)
                sheet.write(i, 44, slip.commission, format1)
                sheet.write(i, 45, slip.installment_refunds, format1)
                sheet.write(i, 46, slip.total_earnings, format1)
                sheet.write(i, 47, slip.employee_id.contract_id.sio_employee_deduction_amount, format1)
                sheet.write(i, 48, slip.miscellaneous_deduction, format1)
                sheet.write(i, 49, slip.employee_id.contract_id.x_fixed_salary, format1)
                sheet.write(i, 50, slip.loan, format1)
                sheet.write(i, 51, slip.penalty, format1)
                sheet.write(i, 52, slip.advance_salary, format1)
                sheet.write(i, 53, slip.credit_purchase, format1)
                sheet.write(i, 54, slip.day_deduction, format1)
                sheet.write(i, 55, slip.traffic_fine, format1)
                sheet.write(i, 56, slip.total_deduction, format1)
                sheet.write(i, 57, slip.employee_id.contract_id.x_gross_salary, format1)
                sheet.write(i, 58, slip.net_wage, format1)
                sheet.write(i, 59, slip.remark, format1)
                i += 1

    # def generate_xlsx_report(self, workbook, data, lines):
    #     format = workbook.add_format({'font_size': 16, 'align': 'vcenter', 'bold': True})
    #     format1 = workbook.add_format({'font_size': 14, 'align': 'vcenter'})
    #     sheet = workbook.add_worksheet('Batch Payslip')
    #     sheet.write(0, 0, 'Beneficiary Account', format)
    #     sheet.write(0, 1, 'Beneficiary Account Title', format)
    #     sheet.write(0, 2, 'Beneficiary Add1', format)
    #     sheet.write(0, 3, 'Transaction Type Code', format)
    #     sheet.write(0, 4, 'Creditor Card Type', format)
    #     sheet.write(0, 5, 'Ordering Customer Account', format)
    #     sheet.write(0, 6, 'Ordering Customer Name', format)
    #     sheet.write(0, 7, 'Remittance Information 1', format)
    #     sheet.write(0, 8, 'Remittance Information 2', format)
    #     sheet.write(0, 9, 'Value D', format)
    #     sheet.write(0, 10, 'currency', format)
    #     sheet.write(0, 11, 'Instructed', format)
    #     sheet.write(0, 12, 'Details of Charge', format)
    #     sheet.write(0, 13, 'Sending Institution Reference for this individual transaction', format)
    #     sheet.write(0, 14, 'Regulatory Reporting 1', format)
    #     sheet.write(0, 15, 'Regulatory Reporting 2', format)
    #     sheet.write(0, 16, 'Regulatory Reporting 3', format)
    #     sheet.write(0, 17, 'Sender To Receiver 1', format)
    #     sheet.write(0, 18, 'Sender To Receiver 2', format)
    #     sheet.write(0, 19, 'Sender To Receiver 3', format)
    #     sheet.write(0, 20, 'Sender To Receiver 4', format)
    #     sheet.write(0, 21, 'Sender To Receiver 5', format)
    #     i = 1
    #     for line in lines:
    #         for slip in line.mapped('slip_ids'):
    #             sheet.write(i, 0, slip.employee_id.bank_account_id.acc_number, format1)
    #             sheet.write(i, 1, slip.employee_id.name, format1)
    #             sheet.write(i, 2, slip.employee_id.address_home_id.city, format1)
    #             sheet.write(i, 3, '021', format1)
    #             sheet.write(i, 4, 'N', format1)
    #             sheet.write(i, 5, line.x_bank_journal_id.bank_account_id.acc_number, format1)
    #             sheet.write(i, 6, line.company_id.name, format1)
    #             sheet.write(i, 7, '/SNDT/CR/93270-1/IBAN', format1)
    #             sheet.write(i, 8, line.x_bank_journal_id.bank_account_id.acc_number, format1)
    #             sheet.write(i, 9, '200630', format1)
    #             sheet.write(i, 10, line.company_id.currency_id.name, format1)
    #             sheet.write(i, 11, slip.net_wage, format1)
    #             sheet.write(i, 12, 'OUR', format1)
    #             i += 1
